services:
  - type: web
    name: dalma-ai-website
    env: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /style.css
        name: Content-Type
        value: text/css
      - path: /script.js
        name: Content-Type
        value: application/javascript

