services:
  # Backend API Server
  - type: web
    name: dalma-ai-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL
        value: gpt-4o-mini

